name: Issues
on: [issues]
jobs:
    issues:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Issue created or edited"
                echo ${{ toJson(github.event) }}

